spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5762
